package net.zf.ezeedecor.exception;

import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.NoHandlerFoundException;

@ControllerAdvice
public class GlobalDefaultExceptionHandler {

	//To handle Error 404 generated by wrong url
	@ExceptionHandler(NoHandlerFoundException.class)
	public ModelAndView handlerNoHandlerFoundException(){
		ModelAndView mv=new ModelAndView("error");
		
		mv.addObject("errorTitle","The page is not constructed");
		mv.addObject("errorDescription","The page you're looking for is not found!");
		mv.addObject("title","Error 404");
		return mv;
	}
	
	@ExceptionHandler(ProductNotFoundException.class)
	public ModelAndView handlerProductNotFoundException(){
		ModelAndView mv=new ModelAndView("error");
		
		mv.addObject("errorTitle","Product not Available");
		mv.addObject("errorDescription","The product you're looking for is not available right now!");
		mv.addObject("title","Product Unavailable");
		return mv;
	}
	
	@ExceptionHandler(Exception.class)
	public ModelAndView handlerException(Exception ex){
		ModelAndView mv=new ModelAndView("error");
		
		mv.addObject("errorTitle","Contact your Administrator!");
		mv.addObject("errorDescription",ex.toString());
		mv.addObject("title","Error");
		return mv;
	}
	
	
}
